# version: "3.9"
# services:
#   api:
#     build:
#       context: .
#       dockerfile: dockerfile
#     container_name: personal-bookmark-api
#     ports:
#       - "3000:3000"
#     environment:
#       - MONGO_URI=mongodb://mongo:27017/bookmarks
#       - NODE_ENV=production
#     depends_on:
#       - mongo

#   mongo:
#     image: mongo:6
#     container_name: personal-bookmark-mongo
#     restart: always
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo_data:/data/db

version: "3"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"