# Use official Node.js image
FROM node:18-alpine

WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Install nodemon globally for hot reload
RUN npm install -g nodemon

# Copy all source files
COPY . .

# Expose port
EXPOSE 3000

# Run app with nodemon for hot reload
CMD ["nodemon", "src/app.ts"]